### ISSUE TITLE
Deprectaed  PublicSuffixList

### ISSUE THREAD

**Issue by MadibaLab** [shivamagarwal-iitb/BlockListParser#1]
When trying to run your code, I am receiving a warning that  psl = PublicSuffixList(), this function is deprecated. does this affect the accuracy of the result?

 I am asking these questions because I noticed some trackers were not identified in my dataset, for example:

top_url:https://www.mcdonalds.com/ca/en-ca.html
Url: https://assets.adobedtm.com/b1e0f2f1c887c13d5a8d850fc709d9f680d2011c/scripts/satellite-590ada0064746d51d6000524.js
content_type: application/x-javascript

Result: The  blocklistparser identified it as non tracker while it was blocked when I activiated the adblock plus extension. I am using both easylist and easyprivacy lists to identify trackers.

**Comment by englehardt** [comment]
> When trying to run your code, I am receiving a warning that psl = PublicSuffixList(), this function is deprecated. does this affect the accuracy of the result?

It could because that warning is related to using an outdated list. I suspect that's not the case here since both domains have a `.com` public suffix and that would be on an outdated list.

The easyprivacy list contains the adobe domain `||adobedtm.com^$third-party`, but it also contains a whitelist exception `@@||adobedtm.com^*/satellite-$script`. It's possible that the request was blocked when you use the ABP extension because a resource that embeds the request was blocked.
